#definition of the basic Classification service
#The treshold for the classification
float64 threshold
#The input objects for the classification
InputObject[] objects
---
#the classification outputs
ObjectClassification[] results